import Head from "next/head";
import Image from "next/image";
import Swiper from "../components/SwiperCards";
import styles from "../styles/Home.module.css";
import { getPhotosData } from "../components/FirebaseUtils";
import Link from "next/link";

export default function Home({ data }) {
  console.log(data);
  const photos = Object.values(data.slidephotos);
  console.log(photos);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/ana-logo.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Nouvel+R&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main className="w-[100%]">
        <div className="home-container w-[100%] flex flex-col items-center justify-center">
          <div className="w-[61%] mt-20 flex justify-between">
            {/* <Link href="/markalarimiz" > */}
            <Link
              href="/markalarimiz"
              className="markalarimiz overflow-hidden cursor-pointer w-[45%] h-[110px] bg-black relative"
            >
              <Image
                width="850"
                height="250"
                className="opacity-25 hover:scale-150 duration-1000"
                src={"/images/anasayfa markalarımız.png"}
              />
              <h2 className="absolute top-8 left-14 font-light tracking-[.6rem] text-slate-100 pointer-events-none">
                Markalarımız
              </h2>
            </Link>
            {/* </Link> */}
            <Link
              href="/hakkimizda"
              className="overflow-hidden cursor-pointer w-[45%] h-[110px] bg-black relative"
            >
              <Image
                width="850"
                height="250"
                className="opacity-25 hover:scale-150 duration-1000 -translate-y-20"
                src={"/images/anasayfa-hakkımızda.jpg"}
              />
              <h2 className="absolute top-8 left-[65px] font-light tracking-[.8rem] text-slate-100 pointer-events-none">
                Hakkımızda
              </h2>
            </Link>
          </div>
          <Swiper photos={photos} />
        </div>
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const data = await getPhotosData();
  return {
    props: {
      data,
    },
  };
};
